### ISSUE TITLE
Consistencia botones

### ISSUE THREAD

**Issue by daviddavo** [JustWhatsTheData/justwhatsthedata.github.io#1]
¡Hola!

En primer lugar, ¡muchas gracias por el fork! Os animo a hacer un Pull Request en jgmd y jdm para añadir un botón a vuestra página, ¡os sorprendería el flujo de visitas que obtenéis!

Y, hablando de botones, si os fijáis en JDM y JGMD, cuando pones el ratón sobre un botón, se pone del color principal, pero un poco más oscuro (como si lo presionaseis), pero vosotros os lo habéis dejado en azul. Para mantener la consistencia en el diseño de las tres páginas, os recomiendo que cambiéis el azul oscuro por rosa oscuro.

![image](https://user-images.githubusercontent.com/10263941/146898277-31a1e48d-6917-4de7-91d7-306e46121fa6.png)

Y también:
- Cuando estás en JDM, el botón está a la derecha y si mantienes el ratón sobre el botón de "Visit JGMD", el fondo es azul (como para simbolizar una transición)
![image](https://user-images.githubusercontent.com/10263941/146899481-5dd3d663-f7aa-4085-87e4-f044b2a65929.png)
- Cuando estás en JGMD, el botón está a la izquierda y si mantienes el ratón sobre el botón de "Visit JDM", el fondo es rojo (como para simbolizar una transición)
![image](https://user-images.githubusercontent.com/10263941/146899595-46dd54e9-31e6-4b5d-9cfe-f4697591b68f.png)

Por lo tando, el botón de "Visit JGMD" debería ser azul oscuro. 

Y, si añadis a JGMD uno de "Visit JWTD", debería ser rosa oscuro y estar situado a la derecha, para que quede algo así como `JDM <-> JGMD <-> JWTD`

Un saludo y suerte con vuestro proyecto!

**Comment by lPoloBlash** [comment]
¡Hola, David!

Perdón por no responderte pero se nos pasó. Muchas gracias por las sugerencias que nos has dado, han sido de gran ayuda. 

Un saludo 😄.
